[project]
name = "xaibo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.10.6",
    "pydantic-yaml>=1.4.0",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
]

[project.optional-dependencies]
webserver = [
    "quart>=0.20.0",
    "quart-cors>=0.8.0",
    "watchfiles>=1.0.4",
]

[dependency-groups]
dev = [
    "devtools>=0.12.2",
]
